teams = ['Bruins', 'Sabres', 'Red Wings', 'Panthers', 'Canadiens', 'Senators', 'Lightning', 'Maple Leafs',
         'Hurricanes', 'Blue Jackets', 'Devils', 'Islanders', 'Rangers', 'Flyers', 'Penguins', 'Capitals',
         'Blackhawks', 'Avalanche', 'Stars', 'Wild', 'Predators', 'Blues', 'Jets',
         'Ducks', 'Coyotes', 'Flames', 'Oilers', 'Kings', 'Sharks', 'Canucks' 'Golden Knights']

abreviations = {'Bruins': 'BOS',
                'Sabres': 'BUF',
                'Red Wings': 'DET',
                'Panthers': 'FLA',
                'Canadiens': 'MTL',
                'Senators': 'OTT',
                'Lightning': 'TBL',
                'Maple Leafs': 'TOR',
                'Hurricanes': 'CAR',
                'Blue Jackets': 'CBJ',
                'Devils': 'NJ',
                'Islanders': 'NYI',
                'Rangers': 'NYR',
                'Flyers': 'PHI',
                'Penguins': 'PIT',
                'Capitals': 'WSH',
                'Blackhawks': 'CHI',
                'Avalanche': 'COL',
                'Stars': 'DAL',
                'Wild': 'MIN',
                'Predators': 'NSH',
                'Blues': 'STL',
                'Jets': 'WPG',
                'Ducks': 'ANH',
                'Coyotes': 'ARI',
                'Flames': 'CGY',
                'Oilers': 'EDM',
                'Kings': 'LAK',
                'Sharks': 'SJS',
                'Canucks':' VAN',
                'Golden Knights': 'VGK'}

endpoint_abreviations = {'Bruins': 'BOS',
                'Sabres': 'BUF',
                'Red Wings': 'DET',
                'Panthers': 'FLA',
                'Canadiens': 'MTL',
                'Senators': 'OTT',
                'Lightning': 'T.B',
                'Maple Leafs': 'TOR',
                'Hurricanes': 'CAR',
                'Blue Jackets': 'CBJ',
                'Devils': 'N.J',
                'Islanders': 'NYI',
                'Rangers': 'NYR',
                'Flyers': 'PHI',
                'Penguins': 'PIT',
                'Capitals': 'WSH',
                'Blackhawks': 'CHI',
                'Avalanche': 'COL',
                'Stars': 'DAL',
                'Wild': 'MIN',
                'Predators': 'NSH',
                'Blues': 'STL',
                'Jets': 'WPG',
                'Ducks': 'ANH',
                'Coyotes': 'ARI',
                'Flames': 'CGY',
                'Oilers': 'EDM',
                'Kings': 'L.A',
                'Sharks': 'S.J',
                'Canucks':' VAN',
                'Golden Knights': 'VGK'}

player_dict_cats = {0: "Player",
                    1: "Position",
                    2: "TOI",
                    3: "CF", 4: "CA", 5: "CF%", 6: "CF% Rel",
                    7: "FF", 8: "FA", 9: "FF%", 10: "FF% Rel",
                    11: "SF", 12: "SA", 13: "SF%", 14: "SF% Rel",
                    15: "GF", 16: "GA", 17: "GF%", 18: "GF% Rel",
                    19: "xGF", 20: "xGA", 21: "xGF%", 22: "xGF% Rel",
                    23: "SCF", 24: "SCA", 25: "SCF%", 26: "SCF% Rel",
                    27: "HDCF", 28: "HDCA", 29: "HDCF%", 30: "HDCF% Rel",
                    31: "OZS", 32: "NZS", 33: "DZS", 34: "OTFS",
                    35: "OZS%", 36: "OZF", 37: "NZF", 38: "DZF", 39: "OZFS%"}

player_numbers = {"Mackenzie Blackwood": 29,
                  "Jesper Boqvist": 90,
                  "Jesper Bratt": 63,
                  "Will Butcher": 8,
                  "Connor Carrick": 5,
                  "Nathan Bastian": 14,
                  "Dmitry Kulikov": 70,
                  "Nikita Gusev": 97,
                  "Ryan Murray": 22,
                  "Nico Hischier": 13,
                  "Jack Hughes": 86,
                  "Michael McLeod": 20,
                  "Ty Smith": 24,
                  "Kyle Palmieri": 21,
                  "Matt Tennyson": 7,
                  "Gilles Senn": 31,
                  "Damon Severson": 28,
                  "Egor Sharangovich": 17,
                  "P.K. Subban": 76,
                  "Sami Vatanen": 45,
                  "Miles Wood": 44,
                  "Pavel Zacha": 37,
                  "Travis Zajac": 19,
                  "Mikhail Maltsev": 23,
                  "Janne Kuokkanen": 59,
                  "Nicholas Merkley": 39,
                  "Andreas Johnsson": 11,
                  "Nolan Foote": 25}

plot_directory = '/home/tylerviducic/Pictures/NST_Bot/'







